[project]
name = "comfyui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "modal>=1.2.0",
    "playwright>=1.55.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
